### ISSUE TITLE
Make verification design changes

### ISSUE THREAD

**Issue by Sukhmai** [GTBitsOfGood/npp#125]
The designers have added a new screen for under verification, and have made alterations to the current verification screens. For this task you will make this new screen, and make all the frontend alterations in line with the design.

Figma:
 - https://www.figma.com/file/uWYrUIldbBLG7PWJplbIxw/NPP-%2F-Spr21?node-id=1599%3A5751
 - https://www.figma.com/file/uWYrUIldbBLG7PWJplbIxw/NPP-%2F-Spr21?node-id=1599%3A5827
 - https://www.figma.com/file/uWYrUIldbBLG7PWJplbIxw/NPP-%2F-Spr21?node-id=1599%3A4889
 - https://www.figma.com/file/uWYrUIldbBLG7PWJplbIxw/NPP-%2F-Spr21?node-id=1599%3A4913
 - https://www.figma.com/file/uWYrUIldbBLG7PWJplbIxw/NPP-%2F-Spr21?node-id=1599%3A5903
 
Relevant Files:
 -`src/screens/App/Verification/index.tsx`

**Comment by matthewbrown77** [comment]
@Sukhmai Where do you think the logic for rendering the new screen should live? Should we have the under verification screen as a separate route or just conditionally render within in the existing verification screen? Since we have enough information to make a decision on which screen to render before the user visits the page, I think it would make sense to do the check on the server-side within the verification Next.js page (although the coding style of the app seems to discourage putting logic there).

**Comment by Sukhmai** [comment]
I think it would make more sense to do it server side. The serve can check the verification status and we can utilize the server for rendering.

**Comment by matthewbrown77** [comment]
We are trying to do the server side render but running into issues with the session for no obvious reasons. Here's the code we are using that is throwing an error:
```
export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const session = await getSession({ req: context.req as any });

    if (session?.user == null) {
      throw new Error("User is not logged in!");
    }

    const organization = await getUserOrg(session);
    const user = await getUserByEmail(session.user.email);
```

Any ideas what could be happening. Relevant commit: https://github.com/GTBitsOfGood/npp/commit/61e1f9b61d476c47fb1800b9faf7d8e1bd72ede6

**Comment by Sukhmai** [comment]
I think I fixed the error. When you call the `getServerSideProps()` function, you are essentially calling database functions inside the client side code. Thus we need to use require syntax inside the  `getServerSideProps()`. 
```js
try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const UserManager = require("&server/mongodb/actions/UserManager");
    const session = await getSession({ req: context.req as any });

    if (session?.user == null) {
      throw new Error("User is not logged in!");
    }

    const organization = await getUserOrg(session);
    const user = await UserManager.getUserByEmail(session.user.email);
```
Let me know if this doesn't work out. I pushed the commit to your branch.

**Comment by matthewbrown77** [comment]
Okay thank you. Either @squagnar or myself will try it out.
