### ISSUE TITLE
Add Bold Visby Font

### ISSUE THREAD

**Issue by chrisjobando** [GTBitsOfGood/npp#80]
See title

**Comment by Josh-McFarlin** [comment]
I believe this is already included in our app in [`src/styles/Fonts.scss`](https://github.com/GTBitsOfGood/npp/blob/master/src/styles/Fonts.scss) with the corresponding file at [`public/static/fonts/VisbyCF-Bold.ttf`](https://github.com/GTBitsOfGood/npp/tree/master/public/static/fonts)

This can be seen in Chrome dev tools by right-clicking a bold element -> computed -> rendered fonts (at the bottom)

![image](https://user-images.githubusercontent.com/32019743/99127045-56d51900-25d5-11eb-83c6-d63c2d2d6db6.png)
