### ISSUE TITLE
Frontend Functionality for Report a Problem

### ISSUE THREAD

**Issue by Sukhmai** [GTBitsOfGood/npp#99]
For this task you will connect the already built pages and add image upload functionality.
![2021-02-02-145144_2560x1440_scrot](https://user-images.githubusercontent.com/39801345/106654592-50b46000-6566-11eb-8476-cbbb9cbe43b0.png)

Tasks:
 1. Add an image upload box that follows the figma design.
 2. Have the File an Issue button lead to the Report Form page.
 3. Verify that the Report Form appropriately submits all the relevant information to the backend.
     - Make sure to pass the uploaded image to the Create Issue function 
 4. Test to make sure the save for later functionality works, and test the form can't submit without all required fields.

Notes:
 - You may have to figure out away to host the image, and then you can push the image url to the backend.

Figma Designs:
 - https://www.figma.com/file/HmqxIOZafhJzAEDal7gJyo/NPP-%2F-Fall20?node-id=686%3A1134
 - https://www.figma.com/file/HmqxIOZafhJzAEDal7gJyo/NPP-%2F-Fall20?node-id=686%3A1190

Relevant Files:
 -  `src/screens/App/ReportForm`
 - `src/screens/App/ReportLanding`
 
Relevant Pull Requests:
 - #72 
 - #83 
 - #70

**Comment by matthewbrown77** [comment]
@Sukhmai Do you know how other bog projects do image hosting for a scenario like this?

**Comment by matthewbrown77** [comment]
Reached out to Daniel and he recommended using Azure Blob storage to capitalize on our free credits. Another option would be Cloudinary, but it has free tier restrictions.

**Comment by Sukhmai** [comment]
Daniel messaged me about it! Thanks for letting me know, and message me over slack if you need anything.

**Comment by matthewbrown77** [comment]
Should users be required to upload an image in order to report a problem?

**Comment by Sukhmai** [comment]
Users aren't required to upload an image to report a problem, but something Tommy mentioned is that it would be useful to clients if they could upload multiple pictures.

**Comment by matthewbrown77** [comment]
![upload image](https://user-images.githubusercontent.com/45107667/107444654-f8063980-6b08-11eb-8b19-c848e12d4170.png)
Posting this as a reference until it gets into figma.
